/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorInicio;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import org.apache.poi.ss.usermodel.*;

/**
 *
 * @author guill
 */
public class JFrameInicio extends javax.swing.JFrame {
    
    
    /**
     * Creates new form JFrameInicio
     */
    public JFrameInicio() {
        initComponents();
        setControlador();
        this.jPanelDatosTrabajador.setVisible(false);
        this.jPanelDatosEmpresa.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanelCifEmpresa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCIF = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonExcel = new javax.swing.JButton();
        jButtonNominas = new javax.swing.JButton();
        jTextFieldNominas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonAyuda = new javax.swing.JButton();
        jPanelDatosEmpresa = new javax.swing.JPanel();
        jLabelEmpresa = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCIF = new javax.swing.JLabel();
        jLabelBruto = new javax.swing.JLabel();
        jLabelTextoCIF = new javax.swing.JLabel();
        jLabelTextoEmpresa = new javax.swing.JLabel();
        jLabelTextoBrutoNomina = new javax.swing.JLabel();
        jPanelDatosTrabajador = new javax.swing.JPanel();
        jLabelTrabajador = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelApellidos1 = new javax.swing.JLabel();
        JLabelNIF = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jLabelNominas = new javax.swing.JLabel();
        jLabelTextoNominas = new javax.swing.JLabel();
        jLabelTextoCategoria = new javax.swing.JLabel();
        jLabelTextoNIF = new javax.swing.JLabel();
        JLabelTextoApellidos = new javax.swing.JLabel();
        jLabelTextoNombre = new javax.swing.JLabel();
        jButtonIzquierda = new javax.swing.JButton();
        jButtonDerecha = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCifEmpresa.setBackground(new java.awt.Color(51, 153, 255));
        jPanelCifEmpresa.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("MES/AÑO");
        jLabel2.setFocusTraversalPolicyProvider(true);

        jTextFieldCIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCIFActionPerformed(evt);
            }
        });

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonExcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonExcel.setText("Excel");
        jButtonExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcelActionPerformed(evt);
            }
        });

        jButtonNominas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonNominas.setText("Nominas");
        jButtonNominas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNominasActionPerformed(evt);
            }
        });

        jTextFieldNominas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNominasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CIF EMPRESA:");
        jLabel3.setFocusTraversalPolicyProvider(true);

        jButtonAyuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAyuda.setText("Ayuda");
        jButtonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCifEmpresaLayout = new javax.swing.GroupLayout(jPanelCifEmpresa);
        jPanelCifEmpresa.setLayout(jPanelCifEmpresaLayout);
        jPanelCifEmpresaLayout.setHorizontalGroup(
            jPanelCifEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCifEmpresaLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanelCifEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanelCifEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCifEmpresaLayout.createSequentialGroup()
                        .addComponent(jTextFieldCIF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCifEmpresaLayout.createSequentialGroup()
                        .addComponent(jTextFieldNominas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCifEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNominas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelCifEmpresaLayout.setVerticalGroup(
            jPanelCifEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCifEmpresaLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanelCifEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonExcel)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCifEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCifEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNominas)
                        .addComponent(jButtonAyuda))
                    .addGroup(jPanelCifEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNominas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.add(jPanelCifEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 100));

        jPanelDatosEmpresa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmpresa.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabelEmpresa.setText("DATOS EMPRESA");
        jPanelDatosEmpresa.add(jLabelEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelNombre.setText("Nombre:");
        jPanelDatosEmpresa.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 30));

        jLabelCIF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCIF.setText("CIF:");
        jPanelDatosEmpresa.add(jLabelCIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 30));

        jLabelBruto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelBruto.setText("Bruto Medio:");
        jPanelDatosEmpresa.add(jLabelBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 30));
        jPanelDatosEmpresa.add(jLabelTextoCIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, 30));
        jPanelDatosEmpresa.add(jLabelTextoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 150, 30));
        jPanelDatosEmpresa.add(jLabelTextoBrutoNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 120, 30));

        jPanel1.add(jPanelDatosEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 220, 280));

        jPanelDatosTrabajador.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatosTrabajador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTrabajador.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabelTrabajador.setText("DATOS TRABAJADOR");
        jPanelDatosTrabajador.add(jLabelTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 30));

        jLabelNombre1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelNombre1.setText("Nombre:");
        jPanelDatosTrabajador.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 46, 70, 20));

        jLabelApellidos1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelApellidos1.setText("Apellidos:");
        jPanelDatosTrabajador.add(jLabelApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, 70, 20));

        JLabelNIF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JLabelNIF.setText("NIF:");
        jPanelDatosTrabajador.add(JLabelNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 106, 60, 20));

        jLabelCategoria.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCategoria.setText("Categoria:");
        jPanelDatosTrabajador.add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 136, 70, 20));

        jLabelNominas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelNominas.setText("Nº Nominas:");
        jPanelDatosTrabajador.add(jLabelNominas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, 80, 20));
        jPanelDatosTrabajador.add(jLabelTextoNominas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 140, 10));
        jPanelDatosTrabajador.add(jLabelTextoCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, 10));
        jPanelDatosTrabajador.add(jLabelTextoNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, 10));
        jPanelDatosTrabajador.add(JLabelTextoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, 10));
        jPanelDatosTrabajador.add(jLabelTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 110, 10));

        jButtonIzquierda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonIzquierda.setText("<-");
        jButtonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzquierdaActionPerformed(evt);
            }
        });
        jPanelDatosTrabajador.add(jButtonIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jButtonDerecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDerecha.setText("->");
        jPanelDatosTrabajador.add(jButtonDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jPanel1.add(jPanelDatosTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCIFActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       
        this.jPanelDatosTrabajador.setVisible(true);
        this.jPanelDatosEmpresa.setVisible(true);
      
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzquierdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIzquierdaActionPerformed

    private void jButtonExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcelActionPerformed

    private void jButtonNominasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNominasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNominasActionPerformed

    private void jTextFieldNominasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNominasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNominasActionPerformed

    private void jButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInicio().setVisible(true);
            }
        });
    }
    
    
    
  
    
    public void setControlador(){
        ControladorInicio controlador=new ControladorInicio(this);
        controlador.setActionBoton();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelNIF;
    private javax.swing.JLabel JLabelTextoApellidos;
    private javax.swing.JButton jButtonAyuda;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonDerecha;
    private javax.swing.JButton jButtonExcel;
    private javax.swing.JButton jButtonIzquierda;
    private javax.swing.JButton jButtonNominas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApellidos1;
    private javax.swing.JLabel jLabelBruto;
    private javax.swing.JLabel jLabelCIF;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNominas;
    private javax.swing.JLabel jLabelTextoBrutoNomina;
    private javax.swing.JLabel jLabelTextoCIF;
    private javax.swing.JLabel jLabelTextoCategoria;
    private javax.swing.JLabel jLabelTextoEmpresa;
    private javax.swing.JLabel jLabelTextoNIF;
    private javax.swing.JLabel jLabelTextoNombre;
    private javax.swing.JLabel jLabelTextoNominas;
    private javax.swing.JLabel jLabelTrabajador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCifEmpresa;
    private javax.swing.JPanel jPanelDatosEmpresa;
    private javax.swing.JPanel jPanelDatosTrabajador;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldCIF;
    private javax.swing.JTextField jTextFieldNominas;
    // End of variables declaration//GEN-END:variables
    
    
    public JLabel getJLabeTextoNombre(){
        return this.jLabelTextoNombre;
    }
    
    public JLabel getJLabeTextoApellidos(){
        return this.JLabelTextoApellidos;
    }
    
    public JLabel getJLabeTextoNIF(){
        return this.jLabelTextoNIF;
    }
    
    public JLabel getJLabeTextoCategoria(){
        return this.jLabelTextoCategoria;
    }
    
    public JLabel getJLabeTextoNumNominas(){
        return this.jLabelTextoNominas;
    }
    
    public JLabel getJLabeTextoBrutoNomina(){
        return this.jLabelTextoBrutoNomina;
    }
    


    public JButton getjButtonBuscar() {
        return this.jButtonBuscar;
    }
    
    public JButton getjButtonAyuda() {
        return this.jButtonAyuda;
    }
    
     public JButton getjButtonNominas() {
        return this.jButtonNominas;
    }
    
    public JButton getjButtonExcel() {
        return this.jButtonExcel;
    }
    
    public JButton getjButtonIzquierda() {
        return this.jButtonIzquierda;
    }
    
    public JButton getjButtonDerecha() {
        return this.jButtonDerecha;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanelCifEmpresa() {
        return jPanelCifEmpresa;
    }

    public void setjPanelCifEmpresa(JPanel jPanelCifEmpresa) {
        this.jPanelCifEmpresa = jPanelCifEmpresa;
    }

    public JPanel getjPanelDatosEmpresa() {
        return jPanelDatosEmpresa;
    }

    public void setjPanelDatosEmpresa(JPanel jPanelDatosEmpresa) {
        this.jPanelDatosEmpresa = jPanelDatosEmpresa;
    }

    public JPanel getjPanelDatosTrabajador() {
        return jPanelDatosTrabajador;
    }

    public void setjPanelDatosTrabajador(JPanel jPanelDatosTrabajador) {
        this.jPanelDatosTrabajador = jPanelDatosTrabajador;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JSplitPane getjSplitPane1() {
        return jSplitPane1;
    }

    public void setjSplitPane1(JSplitPane jSplitPane1) {
        this.jSplitPane1 = jSplitPane1;
    }

    public JTextField getjTextFieldCIF() {
        return jTextFieldCIF;
    }
    
     public JTextField getjTextFieldNominas() {
        return jTextFieldNominas;
    }

    public void setjTextFieldCIF(JTextField jTextFieldCIF) {
        this.jTextFieldCIF = jTextFieldCIF;
    }

    public JLabel getJLabelTextoEmpresa() {
        return this.jLabelTextoEmpresa;
    }

    public JLabel getJLabelTextoCIF() {
        return this.jLabelTextoCIF;
    }
    
    public void showMessageEmpresaCIF(){
        JOptionPane.showMessageDialog(this,"No existe una empresa con ese CIF");
    }
    
    public void showMessageFicherosGenerados(){
        JOptionPane.showMessageDialog(this,"Ficheros Excel y XML creados con exito");
    }
    
    public void showMessageNominasGeneradas(){
        JOptionPane.showMessageDialog(this,"Las nominas se han generado correctamente");
    }
    
    public void showMessageAyuda(){
        JOptionPane.showMessageDialog(this,"Introduzca el CIF y pulse Buscar para mostrar los trabajodores de la empresa \nPulse Excel para completar el fichero \n"
                + "Para imprimir las nominas, pulse Excel, indique la fecha y pulse Nominas.");
    }
    
    public void showMessageEmpresaTrabajadores(){
        JOptionPane.showMessageDialog(this,"Esta empresa no tiene trabajadores");
    }

    
}
