/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author guill
 */
public class JFrameNominas extends javax.swing.JFrame {

    /**
     * Creates new form JFrameNominas
     */
    public JFrameNominas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelDatosTrabajador = new javax.swing.JPanel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelApellidos1 = new javax.swing.JLabel();
        JLabelNIF = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jLabelNominas = new javax.swing.JLabel();
        jLabelTextoNominas = new javax.swing.JLabel();
        jLabelTextoCategoria = new javax.swing.JLabel();
        jLabelTextoNIF = new javax.swing.JLabel();
        JLabelTextoApellidos = new javax.swing.JLabel();
        jLabelTextoNombre = new javax.swing.JLabel();
        jButtonIzquierda = new javax.swing.JButton();
        jButtonDerecha = new javax.swing.JButton();
        jLabelTrabajador2 = new javax.swing.JLabel();
        jLabelNombre2 = new javax.swing.JLabel();
        jLabelTextoNombre1 = new javax.swing.JLabel();
        jLabelApellidos2 = new javax.swing.JLabel();
        JLabelTextoApellidos1 = new javax.swing.JLabel();
        JLabelNIF1 = new javax.swing.JLabel();
        jLabelTextoNIF1 = new javax.swing.JLabel();
        jLabelMes = new javax.swing.JLabel();
        jLabelTextoMes = new javax.swing.JLabel();
        jLabelCategoria2 = new javax.swing.JLabel();
        jLabelTextoCategoria2 = new javax.swing.JLabel();
        jLabelTextoAño = new javax.swing.JLabel();
        jLabelMes1 = new javax.swing.JLabel();
        jLabelTextoTrienios = new javax.swing.JLabel();
        jLabelTrienios = new javax.swing.JLabel();
        jLabelTrienios1 = new javax.swing.JLabel();
        jLabelTextoTrienios1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDatosTrabajador.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatosTrabajador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelNombre1.setText("Nombre:");
        jPanelDatosTrabajador.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 70, 20));

        jLabelApellidos1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelApellidos1.setText("Apellidos:");
        jPanelDatosTrabajador.add(jLabelApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 70, 20));

        JLabelNIF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JLabelNIF.setText("NIF:");
        jPanelDatosTrabajador.add(JLabelNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 60, 20));

        jLabelCategoria.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCategoria.setText("Categoria:");
        jPanelDatosTrabajador.add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 70, 20));

        jLabelNominas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelNominas.setText("Nº Nominas:");
        jPanelDatosTrabajador.add(jLabelNominas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 80, 20));
        jPanelDatosTrabajador.add(jLabelTextoNominas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 140, 10));
        jPanelDatosTrabajador.add(jLabelTextoCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 140, 10));
        jPanelDatosTrabajador.add(jLabelTextoNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 140, 10));
        jPanelDatosTrabajador.add(JLabelTextoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 140, 10));
        jPanelDatosTrabajador.add(jLabelTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 110, 10));

        jButtonIzquierda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonIzquierda.setText("<-");
        jButtonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzquierdaActionPerformed(evt);
            }
        });
        jPanelDatosTrabajador.add(jButtonIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jButtonDerecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDerecha.setText("->");
        jPanelDatosTrabajador.add(jButtonDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        jLabelTrabajador2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabelTrabajador2.setText("DATOS NOMINA");
        jPanelDatosTrabajador.add(jLabelTrabajador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 30));

        jLabelNombre2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelNombre2.setText("Nombre:");
        jPanelDatosTrabajador.add(jLabelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 46, 70, 20));
        jPanelDatosTrabajador.add(jLabelTextoNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 110, 10));

        jLabelApellidos2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelApellidos2.setText("Apellidos:");
        jPanelDatosTrabajador.add(jLabelApellidos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, 70, 20));
        jPanelDatosTrabajador.add(JLabelTextoApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, 10));

        JLabelNIF1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JLabelNIF1.setText("NIF:");
        jPanelDatosTrabajador.add(JLabelNIF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 106, 60, 20));
        jPanelDatosTrabajador.add(jLabelTextoNIF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, 10));

        jLabelMes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelMes.setText("Mes:");
        jPanelDatosTrabajador.add(jLabelMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 20));
        jPanelDatosTrabajador.add(jLabelTextoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, 10));

        jLabelCategoria2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCategoria2.setText("Categoria:");
        jPanelDatosTrabajador.add(jLabelCategoria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 136, 70, 20));
        jPanelDatosTrabajador.add(jLabelTextoCategoria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, 10));
        jPanelDatosTrabajador.add(jLabelTextoAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, 10));

        jLabelMes1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelMes1.setText("Año:");
        jPanelDatosTrabajador.add(jLabelMes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 20));
        jPanelDatosTrabajador.add(jLabelTextoTrienios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 10));

        jLabelTrienios.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelTrienios.setText("Trienios:");
        jPanelDatosTrabajador.add(jLabelTrienios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, 20));

        jLabelTrienios1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelTrienios1.setText("Trienios:");
        jPanelDatosTrabajador.add(jLabelTrienios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, 20));
        jPanelDatosTrabajador.add(jLabelTextoTrienios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 140, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDatosTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelDatosTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzquierdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIzquierdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNominas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNominas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNominas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNominas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNominas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelNIF;
    private javax.swing.JLabel JLabelNIF1;
    private javax.swing.JLabel JLabelTextoApellidos;
    private javax.swing.JLabel JLabelTextoApellidos1;
    private javax.swing.JButton jButtonDerecha;
    private javax.swing.JButton jButtonIzquierda;
    private javax.swing.JLabel jLabelApellidos1;
    private javax.swing.JLabel jLabelApellidos2;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelCategoria2;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelMes1;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNominas;
    private javax.swing.JLabel jLabelTextoAño;
    private javax.swing.JLabel jLabelTextoCategoria;
    private javax.swing.JLabel jLabelTextoCategoria2;
    private javax.swing.JLabel jLabelTextoMes;
    private javax.swing.JLabel jLabelTextoNIF;
    private javax.swing.JLabel jLabelTextoNIF1;
    private javax.swing.JLabel jLabelTextoNombre;
    private javax.swing.JLabel jLabelTextoNombre1;
    private javax.swing.JLabel jLabelTextoNominas;
    private javax.swing.JLabel jLabelTextoTrienios;
    private javax.swing.JLabel jLabelTextoTrienios1;
    private javax.swing.JLabel jLabelTrabajador2;
    private javax.swing.JLabel jLabelTrienios;
    private javax.swing.JLabel jLabelTrienios1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDatosTrabajador;
    // End of variables declaration//GEN-END:variables
}
