/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import de.feig.FEDM.Core.FeException;
import de.feig.FEDM.Core.IHmTableGroup;
import de.feig.FEDM.Core.ReaderCommand.ReaderCommand;
import de.feig.FEDM.Core.ReaderModule;

/**
 *
 * @author Esteban
 */
public class Inventory extends javax.swing.JDialog {

    /**
     * Creates new form Inventory
     */
    public Inventory(java.awt.Frame parent, boolean modal, ReaderModule reader) {
        super(parent, modal);
        this.reader = reader;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Inventory() {
        int back = 0;
        IHmTableGroup.HmTableItem item;

        try {
            // settings for the next sendProtocol
            // sub command: Inventory
            reader.ICmd.setCommandPara(ReaderCommand._0xB0.SUB_COMMAND, (byte) 0x01);
            // mode: no option flags
            reader.ICmd.setCommandPara(ReaderCommand._0xB0.SubCmd._0x01.Req.MODE, (byte) 0x00);
            // clear internal Host Mode Table for next Inventory
            reader.IHmTable.reset();
            // execute Inventory
            back = reader.ICmd.sendProtocol((byte) 0xB0);
            if (back == 0x00) {
            // query table data
                for (int idx = 0; idx < reader.IHmTable.getLength(); idx++) {
                      item = reader.IHmTable.getItemByIndex(idx);
                   //   jTextField1.setText(item.toString());
                      
                      for(int i = 0; i<item.IDD.length;i++){
                          jTextField1.setText(jTextField1.getText()+Integer.toHexString(item.IDD[i])+"/");
                          jTextField2.setText(jTextField2.getText()+(item.IDD[i]&0xff) + "|");
                          System.out.println(jTextField1.getText());
                      }
                      System.out.println(item.IDD.length);
                      
                     
             // get access to public members of the table item
                }
            }
        } catch (FeException ex) {
           javax.swing.JOptionPane.showMessageDialog(this, ex.toString(),
                            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
     private ReaderModule reader;
}
